name: docs

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Setup Deno
                uses: denoland/setup-deno@v2
                with:
                      deno-version: v2.x

            -   name: Install Dependencies
                run: deno i --allow-scripts

            -   name: Build
                run: deno task build

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Add CNAME
                run: echo 'lottie-to-webp.crec.dev' > ./build/CNAME

            -   name: Deploy pages
                uses: actions/deploy-pages@v4
                id: deploy
                with:
                    name: gh-pages
                    path: ./build
