name: pages

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Setup Deno
                uses: denoland/setup-deno@v2
                with:
                      deno-version: v2.x

            -   name: Cache Dependencies
                uses: actions/cache@v4
                id: cache-dependencies
                with:
                    path: node_modules
                    key: ${{ runner.os }}-node-${{ hashFiles('**/deno.lock') }}

            -   name: Install Dependencies
                if: steps.cache-dependencies.outputs.cache-hit != 'true'
                run: deno i --allow-scripts

            -   name: Build
                run: deno task build

            -   name: Add CNAME
                run: echo 'lottie-to-webp.crec.dev' > ./build/CNAME

            -   name: Upload static files as artifact
                id: deploy
                uses: actions/upload-pages-artifact@v3
                with:
                    path: ./build

    deploy:
        permissions:
            id-token: write
            pages: write
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Deploy pages
                uses: actions/deploy-pages@v4
                id: deploy
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
